# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 08:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sem', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
                ('Dob', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rollno', models.IntegerField(unique=True)),
                ('Password', models.CharField(max_length=100)),
                ('Semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_chatbot.Class')),
            ],
        ),
    ]
